export default {
  55110100: {
    Qashqadaryo: [
      "Davolash ishi (G'uzor tumani)",
      "Davolash ishi (Dehqonobod tumani)",
      "Davolash ishi (Qarshi tumani)",
      "Davolash ishi (Kasbi tumani)",
      "Davolash ishi (Kitob tumani)",
      "Davolash ishi (Qamashi tumani)",
      "Davolash ishi (Koson tumani)",
      "Davolash ishi (Mirishkor tumani)",
      "Davolash ishi (Muborak tumani)",
      "Davolash ishi (Nishon tumani)",
      "Davolash ishi (Chiroqchi tumani)",
      "Davolash ishi (Ko'kdala tumani)",
      "Davolash ishi (Shahrisabz tumani)",
      "Davolash ishi (Yakkabog' tumani)",
    ],
    Surxondaryo: [
      "Davolash ishi (Termiz shahri)",
      "Davolash ishi (Angor tumani)",
      "Davolash ishi (Bandixon tumani)",
      "Davolash ishi (Boysun tumani)",
      "Davolash ishi (Denov tumani)",
      "Davolash ishi (Jarqo'rg'on tumani)",
      "Davolash ishi (Qiziriq tumani)",
      "Davolash ishi (Qumqo'rg'on tumani)",
      "Davolash ishi (Muzrabot tumani)",
      "Davolash ishi (Oltinsoy tumani)",
      "Davolash ishi (Sariosiyo tumani)",
      "Davolash ishi (Termiz tumani)",
      "Davolash ishi (Uzun tumani)",
      "Davolash ishi (Uzun tumani Bobotog' hududi)",
      "Davolash ishi (Sherobod tumani)",
      "Davolash ishi (Sho'rchi tumani)",
    ],
  },
  55110200: {
    Surxondaryo: [
      "Pediatriya ishi (Termiz shahri)",
      "Pediatriya ishi (Angor tumani)",
      "Pediatriya ishi (Bandixon tumani)",
      "Pediatriya ishi (Boysun tumani)",
      "Pediatriya ishi (Denov tumani)",
      "Pediatriya ishi (Jarqo'rg'on tumani)",
      "Pediatriya ishi (Qiziriq tumani)",
      "Pediatriya ishi (Qumqo'rg'on tumani)",
      "Pediatriya ishi (Muzrabot tumani)",
      "Pediatriya ishi (Oltinsoy tumani)",
      "Pediatriya ishi (Sariosiyo tumani)",
      "Pediatriya ishi (Termiz tumani)",
      "Pediatriya ishi (Uzun tumani)",
      "Pediatriya ishi (Sherobod tumani)",
      "Pediatriya ishi (Sho'rchi tumani)",
    ],
  },
  "55111100": undefined,
};
